-- Generated by nwg-displays on 2026-06-27 at 20:58:00. Do not edit manually.

hl.monitor({
    output = "desc:Chimei Innolux Corporation 0x14E7",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    mirror = "HDMI-A-1"
})
hl.monitor({
    output = "desc:Philips Consumer Electronics Company PHL 223V7 0x00000122",
    disabled = true
})
